name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Setup Base
        id: nx-base
        run: echo "::set-output name=base::$(git rev-parse HEAD~1)"

      - name: Deploy
        env:
          USE_SSH: true
          GIT_USER: git
          NX_BASE: ${{ steps.nx-base.outputs.base }}
        run: |
          git config --global user.email "alonsovla@gmail.com"
          git config --global user.name "Vladimir Salvador"

          npm run affected -- --target=deploy --base=$NX_BASE
