name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch changes
        run: git fetch

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Setup NX Base
        id: nx-base
        run: echo "::set-output name=base::$(git log --format=%H -n 1 origin/${{ github.base_ref }})"

      - name: Testing
        env:
          NX_BASE: ${{ steps.nx-base.outputs.base }}
        run: |
          npm run lint-staged
          npm run affected:lint -- --base=$NX_BASE


  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch changes
        run: git fetch

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Setup NX Base
        id: nx-base
        run: echo "::set-output name=base::$(git log --format=%H -n 1 origin/${{ github.base_ref }})"

      - name: Testing
        env:
          NX_BASE: ${{ steps.nx-base.outputs.base }}
        run: |
          npm run affected:test -- --base=$NX_BASE

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch changes
        run: git fetch

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Setup NX Base
        id: nx-base
        run: echo "::set-output name=base::$(git log --format=%H -n 1 origin/${{ github.base_ref }})"

      - name: Setup local env
        env:
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }
          NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY }
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }
          NEXT_PUBLIC_FIREBASE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_BUCKET }
          NEXT_PUBLIC_FIREBASE_MESSAGING_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_ID }
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }
        run: |
          touch .env
          echo $FIREBASE_CLIENT_EMAIL >> .env
          echo $FIREBASE_PRIVATE_KEY >> .env
          echo $NEXT_PUBLIC_FIREBASE_PROJECT_ID >> .env
          echo $NEXT_PUBLIC_FIREBASE_DATABASE_URL >> .env
          echo $NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY >> .env
          echo $NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN >> .env
          echo $NEXT_PUBLIC_FIREBASE_BUCKET >> .env
          echo $NEXT_PUBLIC_FIREBASE_MESSAGING_ID >> .env
          echo $NEXT_PUBLIC_FIREBASE_APP_ID >> .env
          echo $NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID >> .env

      - name: Testing
        env:
          NX_BASE: ${{ steps.nx-base.outputs.base }}
        run: |
          echo .env

          npm run affected:build -- --base=$NX_BASE
