name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch changes
        run: git fetch

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Setup NX Base
        id: nx-base
        run: echo "::set-output name=base::$(git log --format=%H -n 1 origin/${{ github.base_ref }})"

      - name: Testing
        env:
          NX_BASE: ${{ steps.nx-base.outputs.base }}
        run: |
          run: npm run affected:test -- --base=$NX_BASE

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch changes
        run: git fetch

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts

      - name: Setup NX Base
        id: nx-base
        run: echo "::set-output name=base::$(git log --format=%H -n 1 origin/${{ github.base_ref }})"

      - name: Testing
        env:
          NX_BASE: ${{ steps.nx-base.outputs.base }}
        run: |
          run: npm run affected:build -- --base=$NX_BASE
